version: '3'
services:
  web:
    image: saksham02/wordies-app
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./main.css:/usr/share/nginx/html/main.css
      - ./app.js:/usr/share/nginx/html/app.js
